import Head from "next/head";

import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DART BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="sample.js" strategy="lazyOnload"></Script>

      <main className={styles.main}>
        <hr
          style={{
            borderColor: "rgb(32,32,32)",
            width: "92vw",
            height: "5px",
          }}
        />
        <h1 className={styles.title}>DART BLOG</h1>
        <p className={styles.description}>The Best Blogs on the Web !</p>
        <hr
          style={{
            borderColor: "rgb(32,32,32)",
            width: "92vw",
            height: "5px",
          }}
        />
        <div className={styles.blog}>
          <h2>Popular Blogs</h2>

          <div className={styles.blogItem}>
            <h3>Javascipt Mastery</h3>
            <p>Javascipt to bahut khatarnak hai</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Javascipt Mastery</h3>
            <p>Javascipt to bahut khatarnak hai</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Javascipt Mastery</h3>
            <p>Javascipt to bahut khatarnak hai</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Javascipt Mastery</h3>
            <p>Javascipt to bahut khatarnak hai</p>
          </div>
        </div>
      </main>
    </div>
  );
}
